CREATE TABLE `respondents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`gender` varchar(50),
	`income` varchar(100),
	`age` int,
	`is_buenos_aires` int DEFAULT 0,
	`children` varchar(50),
	`aversion1` int,
	`aversion2` int,
	`aversion3` int,
	`aversion4` int,
	`confidence1` int,
	`confidence2` int,
	`confidence3` int,
	`confidence4` int,
	`confidence5` int,
	`confidence6` int,
	`confidence7` int,
	`confidence8` int,
	`confidence9` int,
	`security1` int,
	`security2` int,
	`security3` int,
	`intention1` int,
	`intention2` int,
	`intention3` int,
	`communication1` int,
	`communication2` int,
	`communication3` int,
	`communication4` int,
	`communication5` int,
	`communication6` int,
	`communication7` int,
	`index_aversion` int DEFAULT 0,
	`index_confidence` int DEFAULT 0,
	`index_security` int DEFAULT 0,
	`index_intention` int DEFAULT 0,
	`index_communication` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `respondents_id` PRIMARY KEY(`id`)
);
